### ISSUE TITLE
Darzustellenden Werte

### ISSUE THREAD

**Issue by ratnanil** [zhaw-biodiversity-monitor/zhaw-biodiversity-monitor.github.io#11]
Darzustellenden Werte: 

(Letzter Wert - erster Wert) / (letztes Jahr - erstes Jahr)

**Comment by ratnanil** [comment]
bei folgenden 23 Plots habe ich nur eine Beobachtung (Spalte *Unique Plot ID*)

1. CH005_10.A1_1
2. CH005_10.A2_1
3. CH005_10.A3_1
4. CH005_10.A4_1
5. CH005_10.I1_1
6. CH005_10.I2_1
7. CH005_10.I3_1
8. CH005_10.I4_1
9. CH005_10.M1_1
10. CH005_10.M2_1
11. CH005_10.M3_1
12. CH005_10.M4_1
13. CH005_10.R1_1
14. CH005_10.R2_1
15. CH005_10.R3_1
16. CH005_10.R4_1
17. CH005_10.Z1_1
18. CH005_10.Z2_1
19. CH005_10.Z3_1
20. CH005_10.Z4_1
21. CH005_2.StrA_18
22. CH005_5.Str_8
23. CH005_8.Str_5

**Comment by juergen-dengler** [comment]
Lieber Nils,

danke für den Hinweis. Da ist dann wohl in unserem Datenfile etwas falsch.
Einstweilen diese Plots einfach ignorieren.

Beste Grüsse,
Jürgen

Am Di., 10. Dez. 2024 um 15:37 Uhr schrieb Nils ***@***.***>:
